name: Server CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew :server:cleanTest :server:test :server:shadowJar
      - uses: actions/upload-artifact@v4
        with:
          name: server-all-jar
          path: server/build/libs/*-all.jar
