name: Server CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true     # <= avoid failing when cache service is down
        continue-on-error: true     # <= belt & braces: don't fail if post-step chokes

      # Build (with a tiny retry for flaky network)
      - name: Build server (retry 2x)
        run: |
          set -e
          ./gradlew :server:cleanTest :server:test || ./gradlew :server:test
          (./gradlew :server:shadowJar) || (./gradlew :server:jar)

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: server-jar
          path: |
            server/build/libs/*-all.jar
            server/build/libs/*.jar
